prooph_service_bus:
  command_buses:
    gitamine_command_bus: ~
  query_buses:
    gitamine_query_bus: ~

services:
  prooph_service_bus.gitamine_query_bus:
    public: true

  Gitamine\Handler\FetchCommittedFilesQueryHandler:
    arguments: ['@subversion.repository']
    public: true
    tags:
      - { name: 'prooph_service_bus.gitamine_query_bus.route_target', message: Gitamine\Query\FetchCommittedFilesQuery }
  Gitamine\Handler\FetchAddedFilesQueryHandler:
    arguments: ['@subversion.repository']
    public: true
    tags:
      - { name: 'prooph_service_bus.gitamine_query_bus.route_target', message: Gitamine\Query\FetchAddedFilesQuery }
  Gitamine\Handler\FetchModifiedFilesQueryHandler:
    arguments: ['@subversion.repository']
    public: true
    tags:
      - { name: 'prooph_service_bus.gitamine_query_bus.route_target', message: Gitamine\Query\FetchModifiedFilesQuery }
  Gitamine\Handler\FetchDeletedFilesQueryHandler:
    arguments: ['@subversion.repository']
    public: true
    tags:
      - { name: 'prooph_service_bus.gitamine_query_bus.route_target', message: Gitamine\Query\FetchDeletedFilesQuery }
  Gitamine\Handler\GetGitamineDirectoryQueryHandler:
    arguments: ['@gitamine.config']
    public: true
    tags:
      - { name: 'prooph_service_bus.gitamine_query_bus.route_target', message: Gitamine\Query\GetGitamineDirectoryQuery }
  Gitamine\Handler\GetGitamineConfigurationQueryHandler:
    arguments: ['@subversion.repository', '@gitamine.config']
    public: true
    tags:
      - { name: 'prooph_service_bus.gitamine_query_bus.route_target', message: Gitamine\Query\GetGitamineConfigurationQuery }
  Gitamine\Handler\GetConfiguratedPluginsQueryHandler:
    arguments: ['@prooph_service_bus.gitamine_query_bus', '@gitamine.config']
    public: true
    tags:
      - { name: 'prooph_service_bus.gitamine_query_bus.route_target', message: Gitamine\Query\GetConfiguratedPluginsQuery }
  Gitamine\Handler\GetProjectDirectoryQueryHandler:
    arguments: ['@gitamine.config']
    public: true
    tags:
      - { name: 'prooph_service_bus.gitamine_query_bus.route_target', message: Gitamine\Query\GetProjectDirectoryQuery }
  Gitamine\Handler\RunPluginCommandHandler:
    arguments: ['@prooph_service_bus.gitamine_query_bus', '@gitamine.config', '@output']
    public: true
    tags:
      - { name: 'prooph_service_bus.gitamine_query_bus.route_target', message: Gitamine\Command\RunPluginCommand }
  Gitamine\Handler\InstallPluginCommandHandler:
    arguments: ['@gitamine.config', '@output']
    public: true
    tags:
      - { name: 'prooph_service_bus.gitamine_query_bus.route_target', message: Gitamine\Command\InstallPluginCommand }
