prooph_service_bus:
  command_buses:
    gitamine_command_bus: ~
  query_buses:
    gitamine_query_bus: ~

services:
  Gitamine\Handler\FetchCommittedFilesHandler:
    arguments: ['@subversion.repository']
    public: true
    tags:
      - { name: 'prooph_service_bus.gitamine_query_bus.route_target', message: Gitamine\Query\FetchCommittedFiles }
  Gitamine\Handler\FetchAddedFilesHandler:
    arguments: ['@subversion.repository']
    public: true
    tags:
      - { name: 'prooph_service_bus.gitamine_query_bus.route_target', message: Gitamine\Query\FetchAddedFiles }
  Gitamine\Handler\FetchModifiedFilesHandler:
    arguments: ['@subversion.repository']
    public: true
    tags:
      - { name: 'prooph_service_bus.gitamine_query_bus.route_target', message: Gitamine\Query\FetchModifiedFiles }
  Gitamine\Handler\FetchDeletedFilesHandler:
    arguments: ['@subversion.repository']
    public: true
    tags:
      - { name: 'prooph_service_bus.gitamine_query_bus.route_target', message: Gitamine\Query\FetchDeletedFiles }
  Gitamine\Handler\GetGitamineDirectoryHandler:
    arguments: []
    public: true
    tags:
      - { name: 'prooph_service_bus.gitamine_query_bus.route_target', message: Gitamine\Query\GetGitamineDirectory }
  Gitamine\Handler\GetProjectDirectoryHandler:
    arguments: []
    public: true
    tags:
      - { name: 'prooph_service_bus.gitamine_query_bus.route_target', message: Gitamine\Query\GetProjectDirectory }
  Gitamine\Handler\GetGitamineConfHandler:
    arguments: ['@subversion.repository']
    public: true
    tags:
      - { name: 'prooph_service_bus.gitamine_query_bus.route_target', message: Gitamine\Query\GetGitamineConf }
